name: CI - AUTH

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests unitaires (Bun)
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1'

      - name: Installation des dépendances
        run: bun install --frozen-lockfile

      - name: Exécution des tests
        run: bun test

  publish:
    name: Publication de l'image Docker
    needs: [test]
    if: github.event_name == 'push'
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
